dmytro_shylko: homework_5 completed
eugene-okulik/con-tango pull request #7
Opened 2024-01-02 17:51 UTC by con-tango

2024-01-04 06:08 UTC, eugene-okulik requested changes

2024-01-04 06:08 UTC, eugene-okulik commented on homework/dmytro_shylko/homework_5/task_1.py
> +"""Module providing a function printing python version."""
Но этот модуль не распечатывает версию питона )))

2024-01-04 06:08 UTC, eugene-okulik commented on homework/dmytro_shylko/homework_5/task_2.py
> +index_1 = str_1.find("42")
Если мы еще при написании программы знаем какое там число, то мы можем просто написать 
```python
print(42 + 10)
```
Но идея в том, что мы пишем программу, которая может сама извлечь число из строки и произвести с ним нужные действия. Здесь нужно найти что-то общее для всех строк. Позиция числа в строке всегда разная, т.к. разное количество текста перед числом. Количество символов в числе тоже разное, но есть в структуре что-то и одинаковое.

2024-01-04 06:08 UTC, eugene-okulik commented on homework/dmytro_shylko/homework_5/task_3.py
> +print(f"Students {', '.join(students)} study these subjects: {', '.join(subjects)}")
👍

2024-01-04 06:08 UTC, eugene-okulik commented on homework/dmytro_shylko/homework_5/task_1.py
> +name, last_name, city, phone, country = person
👍

2024-01-04 06:47 UTC, con-tango commented on homework/dmytro_shylko/homework_5/task_1.py
> +"""Module providing a function printing python version."""
это чтобы pylint в VS не ругался:
_Missing module docstring pylint(missing-module-docstring - C0114)_

2024-01-04 06:49 UTC, eugene-okulik commented on homework/dmytro_shylko/homework_5/task_1.py
> +"""Module providing a function printing python version."""
Ну, в программировании же как - если ты что-то пишешь, то это должно быть не просто так. Если хочется добавить докстринг, чтобы пайлинт не ругался, то нужно написать докстринг, относящийся к той программе, которую пишешь.

2024-01-04 07:18 UTC, con-tango commented
приветик!
исправил код, достринги, пока не разобрался, убрал

2024-01-05 07:43 UTC, eugene-okulik approved these changes
Если хочется чтобы линт не ругался, то в докстринги, как вариант, можно добавлять текст задания, которое выполняешь, например.

2024-01-05 07:43 UTC, eugene-okulik commented on homework/dmytro_shylko/homework_5/task_2.py
> +index_1 = str_1.find(":") + 2
👍

2024-01-05 07:44 UTC, merged